version: '3.9'

services:
  # Backend AdonisJS
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3333:3333"       # Expose le port 3333 pour le backend
    depends_on:
      - db                # Attend que la DB soit prête
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: obrail_db
    volumes:
      - ./backend:/app

  # Frontend React
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"           # Accessible depuis le navigateur
    depends_on:
      - backend

  # Base de données PostgreSQL
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: obrail_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
